### ISSUE TITLE
fix: expect const val fails to compile with Kotlin 2.x (K2 compiler)

### ISSUE THREAD

**Issue by yshrsmz** [yshrsmz/BuildKonfig#277]
## Description

With Kotlin 2.x (K2 compiler), `expect const val` without an initializer causes a compilation error, even with `@Suppress("CONST_VAL_WITHOUT_INITIALIZER")`.

This was originally reported as a warning in #148 (Kotlin 2.0 RC), but has now become a **compilation error** in Kotlin 2.3+.

### Error

```
e: org.jetbrains.kotlin.util.SourceCodeAnalysisException: java.lang.IllegalArgumentException:
Const property has no const initializer expression.
Got @R|kotlin/Suppress|(names = vararg(String(CONST_VAL_WITHOUT_INITIALIZER)))
public final expect const val VERSION_NAME: R|kotlin/String|
```

### Reproduction

Any BuildKonfig project with `const = true` fields and target-specific configs (which triggers the expect/actual generation path) will fail to compile with Kotlin 2.3+.

```kotlin
buildkonfig {
    packageName = "com.example"
    defaultConfigs {
        buildConfigField(Type.STRING, "VERSION_NAME", "1.0.0", const = true)
    }
    targetConfigs {
        create("jvm") {
            buildConfigField(Type.STRING, "target", "jvm")
        }
    }
}
```

### Current generated code (broken)

```kotlin
// commonMain (expect)
expect object BuildKonfig {
    @Suppress("CONST_VAL_WITHOUT_INITIALIZER")
    const val VERSION_NAME: String  // ← K2 compiler error
}

// jvmMain (actual)
actual object BuildKonfig {
    actual const val VERSION_NAME: String = "1.0.0"
}
```

### Proposed fix

Generate `expect val` (without `const`) on the expect side, and `actual const val` on the actual side. This is valid Kotlin — see [KT-18856](https://youtrack.jetbrains.com/issue/KT-18856/Can-we-have-expect-actual-consts).

```kotlin
// commonMain (expect)
expect object BuildKonfig {
    val VERSION_NAME: String  // no const, no @Suppress
}

// jvmMain (actual)
actual object BuildKonfig {
    actual const val VERSION_NAME: String = "1.0.0"
}
```

### Related Kotlin issues

- [KT-67371](https://youtrack.jetbrains.com/issue/KT-67371/K2-2.0.0-RC1-compiler-bug-const-val-property-must-have-a-const-initializer) — K2: const val property must have a const initializer
- [KT-67330](https://youtrack.jetbrains.com/issue/KT-67330/Kotlin-2.0-RC1-const-val-property-must-have-a-const-initializer) — Kotlin 2.0 RC1: const val property must have a const initializer
- [KT-18856](https://youtrack.jetbrains.com/issue/KT-18856/Can-we-have-expect-actual-consts) — expect val + actual const val pattern
